/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ltud;

import java.awt.print.PrinterException;
import java.io.File;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.MessageFormat;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author 08567
 */
public class DANHTHU extends javax.swing.JFrame {
    private EmployeeProducts parent;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DANHTHU.class.getName());

    /**
     * Creates new form DANHTHU
     */
    public DANHTHU(EmployeeProducts parent) {
        initComponents();
        this.parent = parent;
        loadChungtu();

    this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            this.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    if (parent != null) {
                        parent.setVisible(true);
                    }
                }
            });        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    void loadChungtu() {
        DecimalFormat formatter = new DecimalFormat("#,###"); 
        DefaultTableModel model = (DefaultTableModel) tableDanhthu.getModel();
        model.setColumnIdentifiers(new String[]{
            "MÃ SP", "TÊN SP", "ĐƠN GIÁ", "SỐ LƯỢNG ĐÃ BÁN", "CHIẾT KHẤU", "THÀNH TIỀN"
        });
        model.setRowCount(0);

        String sql = """
            SELECT 
                sp.MASP, 
                sp.TENSP, 
                SUM(ct.SOLUONG) AS TONG_SOLUONG, 
                ct.CHIETKHAU,
                ct.DONGIA, 
                SUM(ct.SOLUONG * ct.DONGIA * (1 - ct.CHIETKHAU / 100)) AS THANHTIEN
            FROM hoa_don hd
            JOIN chi_tiet_hoa_don ct ON hd.MAHD = ct.MAHD
            JOIN san_pham sp ON sp.MASP = ct.MASP
            GROUP BY sp.MASP, sp.TENSP, ct.DONGIA, ct.CHIETKHAU
        """;

        double tongDanhThu = 0;

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                double dongia = rs.getDouble("DONGIA");
                int soluong = rs.getInt("TONG_SOLUONG");
                int chietkhau = rs.getInt("CHIETKHAU");
                double thanhtien = rs.getDouble("THANHTIEN");

                tongDanhThu += thanhtien;

                Object[] row = {
                    rs.getString("MASP"),
                    rs.getString("TENSP"),
                    formatter.format(dongia),
                    soluong,
                    chietkhau + " %",
                    formatter.format(thanhtien) + " VNĐ"
                };
                model.addRow(row);
            }

            txtTongdanhthu.setText(formatter.format(tongDanhThu) + " VNĐ");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải sản phẩm đã bán: " + e.getMessage());
        }
    }

    public void exportToExcel(JTable table, String filePath) {
        Workbook workbook = new XSSFWorkbook();
        Sheet sheet = workbook.createSheet("Doanh thu");

        TableModel model = table.getModel();

        // Tạo font in đậm cho header
        CellStyle headerStyle = workbook.createCellStyle();
        Font font = workbook.createFont();
        font.setBold(true);
        headerStyle.setFont(font);

        // Header
        Row header = sheet.createRow(0);
        for (int i = 0; i < model.getColumnCount(); i++) {
            Cell cell = header.createCell(i);
            cell.setCellValue(model.getColumnName(i));
            cell.setCellStyle(headerStyle);
        }

        // Data
        for (int rowIndex = 0; rowIndex < model.getRowCount(); rowIndex++) {
            Row row = sheet.createRow(rowIndex + 1);
            for (int colIndex = 0; colIndex < model.getColumnCount(); colIndex++) {
                Cell cell = row.createCell(colIndex);
                Object value = model.getValueAt(rowIndex, colIndex);

                if (value == null) {
                    cell.setCellValue("");
                    continue;
                }

                String text = value.toString().replace(" VNĐ", "").replace(",", "").replace(" %", "");

                try {
                    // Nếu là cột số (ĐƠN GIÁ, THÀNH TIỀN, SỐ LƯỢNG, CHIẾT KHẤU)
                    double number = Double.parseDouble(text);
                    cell.setCellValue(number);
                } catch (NumberFormatException e) {
                    cell.setCellValue(value.toString());
                }
            }
        }

        // Auto resize
        for (int i = 0; i < model.getColumnCount(); i++) {
            sheet.autoSizeColumn(i);
        }

        try (FileOutputStream out = new FileOutputStream(filePath)) {
            workbook.write(out);
            workbook.close();
            JOptionPane.showMessageDialog(null, "Xuất Excel thành công!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Lỗi khi xuất Excel: " + e.getMessage());
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableDanhthu = new javax.swing.JTable();
        btnXuatEcecl = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblDanhthu = new javax.swing.JLabel();
        txtTongdanhthu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Báo cáo danh thu");

        tableDanhthu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableDanhthu);

        btnXuatEcecl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXuatEcecl.setForeground(new java.awt.Color(0, 0, 255));
        btnXuatEcecl.setText("Xuất Execl");
        btnXuatEcecl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatEceclActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(0, 51, 255));
        btnThoat.setText("Thoát ");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIn.setForeground(new java.awt.Color(0, 0, 255));
        btnIn.setText("In");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BÁO CÁO DANH THU");

        lblDanhthu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDanhthu.setForeground(new java.awt.Color(255, 0, 51));
        lblDanhthu.setText("Tổng danh thu:");

        txtTongdanhthu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTongdanhthu.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnXuatEcecl, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblDanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTongdanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDanhthu)
                    .addComponent(txtTongdanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatEcecl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        try {
            MessageFormat header = new MessageFormat("BÁO CÁO DOANH THU");
            MessageFormat footer = new MessageFormat("Tổng doanh thu: " + txtTongdanhthu.getText());

            boolean complete = tableDanhthu.print(
                JTable.PrintMode.FIT_WIDTH, 
                header,
                footer
            );

            if (complete) {
                JOptionPane.showMessageDialog(this, "In thành công");
            } else {
                JOptionPane.showMessageDialog(this, "In bị hủy");
            }
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi khi in: " + ex.getMessage());
        }     
    }//GEN-LAST:event_btnInActionPerformed

    private void btnXuatEceclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatEceclActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn nơi lưu file Excel");

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();

            if (!filePath.toLowerCase().endsWith(".xlsx")) {
                filePath += ".xlsx";
            }

            exportToExcel(tableDanhthu, filePath);
        }
    
    }//GEN-LAST:event_btnXuatEceclActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose(); // đóng form DANHTHU
        if (parent != null) {
            parent.setVisible(true); // hiện lại form cha
        }       
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new DANHTHU(null).setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXuatEcecl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDanhthu;
    private javax.swing.JTable tableDanhthu;
    private javax.swing.JTextField txtTongdanhthu;
    // End of variables declaration//GEN-END:variables
}

