/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ltud;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Edit_KM extends javax.swing.JFrame {
    private String MAKM,TENKM,PHANTRAMGIAM, NGAYBATDAU, NGAYKETTHUC;
    private Manage_Khuyenmai parent;
    public Edit_KM(Manage_Khuyenmai parent, String MAKM, String TENKM, String PHANTRAMGIAM, String NGAYBATDAU, String NGAYKETTHUC) {
        initComponents();
        this.parent = parent;
        this.MAKM = MAKM;
        this.TENKM = TENKM;
        this.PHANTRAMGIAM = PHANTRAMGIAM;
        this.NGAYBATDAU = NGAYBATDAU;
        this.NGAYKETTHUC = NGAYKETTHUC;
        txt_MaKM.setText(MAKM);
        txt_TenKM.setText(TENKM);
        txt_PT.setText(PHANTRAMGIAM);
        txt_NgayBD.setText(NGAYBATDAU);
        txt_NgayKT.setText(NGAYKETTHUC);

//        cmbRole.setSelectedItem(role);
//        cmbStatus.setSelectedItem(status);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
               parent.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_edit = new javax.swing.JLabel();
        lbl_MaKM = new javax.swing.JLabel();
        lbl_TenKM = new javax.swing.JLabel();
        lbl_PT = new javax.swing.JLabel();
        lbl_NgayBD = new javax.swing.JLabel();
        txt_TenKM = new javax.swing.JTextField();
        txt_MaKM = new javax.swing.JTextField();
        btnUpDate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lbl_NgayBD1 = new javax.swing.JLabel();
        txt_PT = new javax.swing.JTextField();
        txt_NgayBD = new javax.swing.JTextField();
        txt_NgayKT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EDIT KHUYẾN MÃI");

        lbl_edit.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        lbl_edit.setForeground(new java.awt.Color(0, 0, 255));
        lbl_edit.setText("EDIT KHUYẾN MÃI");

        lbl_MaKM.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_MaKM.setText("Mã KM:");

        lbl_TenKM.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_TenKM.setText("Tên KM:");

        lbl_PT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_PT.setText("Phần trăm giảm:");

        lbl_NgayBD.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_NgayBD.setText("Ngày bắt đầu:");

        txt_TenKM.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_TenKM.setToolTipText("Nhập Tên KM");

        txt_MaKM.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_MaKM.setToolTipText("Nhập Mã KM");

        btnUpDate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnUpDate.setText("UpDate");
        btnUpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpDateActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lbl_NgayBD1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_NgayBD1.setText("Ngày bắt đầu:");

        txt_PT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_PT.setToolTipText("Nhập Tên KM");

        txt_NgayBD.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_NgayBD.setToolTipText("Nhập Tên KM");

        txt_NgayKT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_NgayKT.setToolTipText("Nhập Tên KM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 326, Short.MAX_VALUE)
                .addComponent(btnUpDate)
                .addGap(52, 52, 52)
                .addComponent(btnReset)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_TenKM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_TenKM, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_MaKM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                        .addComponent(txt_MaKM, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_NgayBD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_NgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_NgayBD1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_NgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_PT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_PT, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(lbl_edit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_edit)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_MaKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_MaKM))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_TenKM)
                    .addComponent(txt_TenKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_PT)
                    .addComponent(txt_PT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NgayBD)
                    .addComponent(txt_NgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NgayBD1)
                    .addComponent(txt_NgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpDate)
                    .addComponent(btnReset))
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpDateActionPerformed
        // TODO add your handling code here:
    String MAKM = txt_MaKM.getText().trim();
    String TENKM = txt_TenKM.getText().trim();
    String PHANTRAMGIAM = txt_PT.getText().trim();
    String NGAYBATDAU = txt_NgayBD.getText().trim();
    String NGAYKETTHUC = txt_NgayKT.getText().trim();

    if (MAKM.isEmpty() || TENKM.isEmpty() || PHANTRAMGIAM.isEmpty() || NGAYBATDAU.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin (ngoại trừ ngày kết thúc)", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        Connection conn = DatabaseConnection.getConnection();
        String sql = "UPDATE khuyen_mai SET TENKM = ?, PHANTRAMGIAM = ?, NGAYBATDAU = ?, NGAYKETTHUC = ?, NGAYSUA = ? WHERE MAKM = ?";
        PreparedStatement ps = conn.prepareCall(sql);
        ps.setString(1, TENKM);
        ps.setString(2, PHANTRAMGIAM);
        ps.setString(3, NGAYBATDAU);

        if (NGAYKETTHUC.isEmpty()) {
            ps.setNull(4, java.sql.Types.DATE);
        } else {
            ps.setString(4, NGAYKETTHUC);
        }

        // Set ngày sửa thành thời gian hiện tại
        ps.setTimestamp(5, new java.sql.Timestamp(System.currentTimeMillis()));

        // WHERE MAKM = ?
        ps.setString(6, MAKM);


        int rows = ps.executeUpdate();
        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Cập nhật dữ liệu thành công", "Thông báo", JOptionPane.OK_OPTION);
            if (parent != null) {
                parent.loadKMData();
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật dữ liệu thất bại!");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
    }
    }//GEN-LAST:event_btnUpDateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txt_TenKM.setText(TENKM);
        txt_MaKM.setText(MAKM);
        txt_PT.setText(PHANTRAMGIAM);
        txt_NgayBD.setText(NGAYBATDAU);
        txt_NgayKT.setText(NGAYKETTHUC);
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new EditUserForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpDate;
    private javax.swing.JLabel lbl_MaKM;
    private javax.swing.JLabel lbl_NgayBD;
    private javax.swing.JLabel lbl_NgayBD1;
    private javax.swing.JLabel lbl_PT;
    private javax.swing.JLabel lbl_TenKM;
    private javax.swing.JLabel lbl_edit;
    private javax.swing.JTextField txt_MaKM;
    private javax.swing.JTextField txt_NgayBD;
    private javax.swing.JTextField txt_NgayKT;
    private javax.swing.JTextField txt_PT;
    private javax.swing.JTextField txt_TenKM;
    // End of variables declaration//GEN-END:variables
}
