/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ltud;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Manage_Danhgia extends javax.swing.JFrame {
    private ManagerForm parent;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Manage_Danhgia.class.getName());
    private final java.util.List<Object[]> danhGiaData = new java.util.ArrayList<>();

    /**
     * Creates new form Manage_Danhgia
     */
    public Manage_Danhgia(ManagerForm parent) {
        initComponents();
        loadDanhGiaData(); // Load dữ liệu ban đầu
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
               parent.setVisible(true);
            }
        });
        cmbLoc.addActionListener(e -> filterByRating());
    }
    void loadDanhGiaData() {
    DefaultTableModel model = (DefaultTableModel) TableDanhgia.getModel();
    model.setColumnIdentifiers(new String[]{"MADANHGIA", "MAKH", "MASP", "DIEM","NHANXET","NGAYDANHGIA"});
    model.setRowCount(0);
    danhGiaData.clear(); // Xóa dữ liệu cũ

    try (Connection con = DatabaseConnection.getConnection()) {
        String sql = "SELECT MADANHGIA, MAKH, MASP, DIEM, NHANXET, NGAYDANHGIA FROM danh_gia";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        while (rs.next()) {
            Object[] row = {
                rs.getString("MADANHGIA"),
                rs.getString("MAKH"),
                rs.getString("MASP"),
                rs.getInt("DIEM"),
                rs.getString("NHANXET"),
                rs.getString("NGAYDANHGIA")
            };
            model.addRow(row);               
            danhGiaData.add(row); 
        } 
        TableDanhgia.removeColumn(TableDanhgia.getColumnModel().getColumn(5));
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + e.getMessage());
    }       
    }
    private void updateTable(List<Object[]> data) {
    DefaultTableModel model = (DefaultTableModel) TableDanhgia.getModel();
    model.setRowCount(0); // Xoá dữ liệu cũ
    for (Object[] row : data) {
        model.addRow(row); // Thêm dòng mới
    }
    }



    private void filterByRating() {
        String selected = cmbLoc.getSelectedItem().toString();
        java.util.List<Object[]> filtered = new java.util.ArrayList<>();

        for (Object[] row : danhGiaData) {
            int diem = (int) row[3];
            if (selected.equals("Tất cả") || selected.equals("Lọc theo điểm")) {
                filtered.add(row);
            } else if (Integer.toString(diem).equals(selected)) {
                filtered.add(row);
            }
        }
        updateTable(filtered);
    }

    private void searchDanhGia() {
        String keyword = txtTim.getText().toLowerCase();
        java.util.List<Object[]> filtered = new java.util.ArrayList<>();

        for (Object[] row : danhGiaData) {
            String maKH = row[1].toString().toLowerCase();
            String maSP = row[2].toString().toLowerCase();
            if (maKH.contains(keyword) || maSP.contains(keyword)) {
                filtered.add(row);
            }
        }
        updateTable(filtered);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDanhgia = new javax.swing.JLabel();
        txtTim = new javax.swing.JTextField();
        cmbLoc = new javax.swing.JComboBox<>();
        lblTim = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDanhgia = new javax.swing.JTable();
        btnDetail = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MANAGE_DANHGIA");

        lblDanhgia.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblDanhgia.setForeground(new java.awt.Color(0, 0, 255));
        lblDanhgia.setText("QUẢN LÝ ĐÁNH GIÁ");

        txtTim.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        cmbLoc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cmbLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lọc theo điểm", "1", "2", "3", "4", "5", "Tất cả" }));

        lblTim.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTim.setText("Tìm kiếm: ");

        TableDanhgia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableDanhgia);

        btnDetail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDetail.setText("Detail");
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnTim.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(lblDanhgia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTim)
                                .addGap(42, 42, 42)
                                .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnTim)
                                .addGap(148, 148, 148)
                                .addComponent(cmbLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(btnDetail)
                        .addGap(96, 96, 96)
                        .addComponent(btnDelete)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblDanhgia)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTim)
                    .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetail)
                    .addComponent(btnDelete))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        // TODO add your handling code here:            
    int selectedRow = TableDanhgia.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) TableDanhgia.getModel();
            String msg = "Mã đánh giá: " + model.getValueAt(selectedRow, 0)
                       + "\nMã KH: " + model.getValueAt(selectedRow, 1)
                       + "\nMã SP: " + model.getValueAt(selectedRow, 2)
                       + "\nĐiểm: " + model.getValueAt(selectedRow, 3)
                       + "\nNhận xét: " + model.getValueAt(selectedRow, 4)
                       + "\nNgày: " + model.getValueAt(selectedRow, 5);
            JOptionPane.showMessageDialog(this, msg, "Chi tiết đánh giá", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xem chi tiết.");
        }
    }//GEN-LAST:event_btnDetailActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:                                        
    int selectedRow = TableDanhgia.getSelectedRow();
        if (selectedRow != -1) {
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa đánh giá này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                DefaultTableModel model = (DefaultTableModel) TableDanhgia.getModel();
                String ma = model.getValueAt(selectedRow, 0).toString();
                try (Connection con = DatabaseConnection.getConnection()) {
                    PreparedStatement pst = con.prepareStatement("DELETE FROM danh_gia WHERE MADANHGIA = ?");
                    pst.setString(1, ma);
                    pst.executeUpdate();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lỗi khi xóa: " + e.getMessage());
                }
                loadDanhGiaData();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa.");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:                           
    String keyword = txtTim.getText().trim().toLowerCase();
    List<Object[]> filtered = new ArrayList<>();

    // Nếu ô tìm kiếm trống thì hiện lại toàn bộ dữ liệu
    if (keyword.isEmpty()) {
        updateTable(danhGiaData);
        return;
    }

    for (Object[] row : danhGiaData) {
        String maKH = row[1].toString().toLowerCase();
        String maSP = row[2].toString().toLowerCase();
        String diem = row[3].toString().toLowerCase();

        // Nếu keyword là số → tìm theo điểm
        if (keyword.matches("\\d+")) {
            if (diem.equals(keyword)) {
                filtered.add(row);
            }
        } else {
            // Ngược lại, tìm theo Mã KH hoặc Mã SP
            if (maKH.contains(keyword) || maSP.contains(keyword)) {
                filtered.add(row);
            }
        }
    }

    updateTable(filtered);
    }//GEN-LAST:event_btnTimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Manage_Danhgia(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableDanhgia;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnTim;
    private javax.swing.JComboBox<String> cmbLoc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDanhgia;
    private javax.swing.JLabel lblTim;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
