/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ltud;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Manage_Khuyenmai extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Manage_Khuyenmai.class.getName());
    /**
     * Creates new form Khuyemmai
     */
    private ManagerForm parent;
    public Manage_Khuyenmai(ManagerForm parent) {
        initComponents();
        loadKMData();
    this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
               parent.setVisible(true);
            }
        });
    }
    void loadKMData() {
       DefaultTableModel model = (DefaultTableModel) TableKM.getModel();
       model.setColumnIdentifiers(new String[]{"MAKM", "TENKM", "PHANTRAMGIAM", "NGAYBATDAU","NGAYKETTHUC", "NGAYTAO", "NGAYSUA"});
       model.setRowCount(0); // Xóa dữ liệu cũ
//       tableUsers.getColumnModel().getColumn(0).setPreferredWidth(30);  // ID
//       tableUsers.getColumnModel().getColumn(1).setPreferredWidth(150); // Username
       
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement("SELECT * FROM khuyen_mai");
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                Object[] row = {
                    rs.getString("MAKM"),
                    rs.getString("TENKM"),
                    rs.getString("PHANTRAMGIAM"),
                    rs.getString("NGAYBATDAU"),
                    rs.getString("NGAYKETTHUC"),
                };
                model.addRow(row);               
               
            } 
            TableKM.removeColumn(TableKM.getColumnModel().getColumn(6));
            //tableUsers.setModel(model); // Gắn model mới cho bảng
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + e.getMessage());
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKM = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableKM = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Khuyến mãi");

        lblKM.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        lblKM.setForeground(new java.awt.Color(0, 0, 255));
        lblKM.setText("QUẢN LÝ KHUYẾN MÃI");

        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        TableKM.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TableKM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableKM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnAdd)
                        .addGap(81, 81, 81)
                        .addComponent(btnEdit)
                        .addGap(68, 68, 68)
                        .addComponent(btnDelete)
                        .addGap(89, 89, 89)
                        .addComponent(btnClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(lblKM))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblKM)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit)
                    .addComponent(btnAdd))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = TableKM.getSelectedRow();
        if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn người dùng để xóa.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        return;
        }
        int option = JOptionPane.showConfirmDialog(this,"Bạn có chắc chắn muốn xóa người dùng này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
        String userID = TableKM.getValueAt(selectedRow, 0).toString();
        try { Connection conn = DatabaseConnection.getConnection();
            String sql = " DELETE from khuyen_mai WHERE MAKM = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, userID);
            int rows = ps.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                loadKMData();// Load lại bảng
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi " + e.getMessage());
        }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Add_KM addForm = new Add_KM(this); 
        addForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedRow = TableKM.getSelectedRow();
         if(selectedRow == -1){
             JOptionPane.showMessageDialog(this,"Vui lòng chọn User để hiệu chỉnh", "Thông báo",JOptionPane.WARNING_MESSAGE);
             return;
         }
         String MAKM = (String) TableKM.getValueAt(selectedRow, 0);
         String TENKM = (String)TableKM.getValueAt(selectedRow, 1);
         String PHANTRAMGIAM = (String)TableKM.getValueAt(selectedRow, 2);
         String NGAYBATDAU = (String)TableKM.getValueAt(selectedRow, 3);
         String NGAYKETTHUC = (String)TableKM.getValueAt(selectedRow, 4);
         Edit_KM editForm = new Edit_KM(this, MAKM, TENKM, PHANTRAMGIAM, NGAYBATDAU, NGAYKETTHUC);
         editForm.setVisible(true);
         this.setVisible(false);
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this,"Bạn muốn thoát?","Thoát!",JOptionPane.YES_NO_OPTION);
        if(option == JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Manage_Khuyenmai(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableKM;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKM;
    // End of variables declaration//GEN-END:variables
}
